#!/usr/bin/python3

import amulet
import requests
import unittest
from lib.TestSosreportCharm import TestSosreportCharm


if __name__ == '__main__':
    deployment_t = TestSosreportCharm(series='trusty')
    deployment_t.run_test()
