#!/usr/bin/python3

from lib.TestSosreportCharm import TestSosreportCharm


if __name__ == '__main__':
    # Skip the test for the time being
    # until https://github.com/juju/amulet/issues/155
    # is fixed (test failing on Xenial)
    import sys
    sys.exit(100)
    # It fails on amulet script expecting py2
    deployment_x = TestSosreportCharm(series='xenial')
    deployment_x.run_test()
