#!/usr/bin/python3

from charmhelpers.core.hookenv import action_get
from charmhelpers.core.hookenv import action_set
from charmhelpers.core.hookenv import config
import sys
import os
import re
import shutil
from subprocess import check_output, CalledProcessError

command = ['sosreport']
default_option = ['--batch']
juju_home = os.environ.get("HOME")
params = action_get()
valid_options = ['options']

try:
    sosrun = check_output(command+default_option, universal_newlines=True)
    regex = re.compile(r' /tmp.*tar.*')
    tarball = regex.findall(sosrun)[0].lstrip(' ')
    md5sum = tarball + '.md5'
    shutil.move(tarball, juju_home)
    shutil.move(md5sum, juju_home)
    action_set({'result-map.message': '%s and %s available in %s'.format(tarball, md5sum, juju_home)})
    action_set({'outcome': 'success'})
    sys.exit(0)
except CalledProcessError:
    pass
