#!/usr/bin/python3

from charmhelpers.core.hookenv import action_get
from charmhelpers.core.hookenv import action_set
from charmhelpers.core.hookenv import DEBUG
from charmhelpers.core.hookenv import log as juju_log
from charmhelpers.core.hookenv import config
import sys
import os
import re
import shutil
from subprocess import check_output, CalledProcessError

command = ['sosreport']
default_option = ['--batch']
juju_home = '/home/ubuntu'
params = action_get()
valid_options = ['options']

try:
    juju_log("Running %s %s" % (command, default_option), level=DEBUG)
    sosrun = check_output(command + default_option, universal_newlines=True)
    regex = re.compile(r' /tmp.*tar.*')
    tarball = regex.findall(sosrun)[0].lstrip(' ')
    md5sum = tarball + '.md5'
    juju_log("Moving %s in %s" % (tarball, juju_home), level=DEBUG)
    shutil.move(tarball, juju_home)
    juju_log("Moving %s in %s" % (md5sum, juju_home), level=DEBUG)
    shutil.move(md5sum, juju_home)
    action_msg = '%s and %s available in %s' % (tarball.lstrip('/tmp/'),
                                                md5sum.lstrip('/tmp/'),
                                                juju_home)
    action_set({'result-map.message': action_msg})
    action_set({'outcome': 'success'})
    sys.exit(0)
except CalledProcessError:
    pass
